import { X, Calendar, Download } from 'lucide-react';

export const planModalUI = {
  motion: {
    backdrop: { initial: { opacity: 0 }, animate: { opacity: 1 }, exit: { opacity: 0 } },
    modal: { initial: { opacity: 0, scale: 0.95, y: 20 }, animate: { opacity: 1, scale: 1, y: 0 }, exit: { opacity: 0, scale: 0.95, y: 20 } },
  },
  overlay: 'fixed inset-0 z-50 flex items-center justify-center p-4',
  backdrop: 'absolute inset-0 bg-black/60 backdrop-blur-sm',
  modal: 'relative w-full max-w-4xl bg-slate-900 border border-white/10 rounded-[2.5rem] shadow-2xl overflow-hidden',
  header: {
    base: 'flex items-center justify-between px-8 py-6 border-b border-white/10',
    title: 'text-xl font-semibold',
    closeButton: 'p-2 text-slate-400 hover:text-white hover:bg-white/10 rounded-xl transition-colors',
    closeIcon: X,
    closeIconSize: 'w-5 h-5',
  },
  body: 'p-8 md:p-10 overflow-y-auto max-h-[80vh] custom-scrollbar',
  summaryGrid: 'grid grid-cols-1 lg:grid-cols-3 gap-8 mb-12',
  paymentCard: {
    base: 'lg:col-span-1 glass-card p-8 rounded-3xl bg-indigo-600/10 border-indigo-500/20',
    label: 'text-slate-400 text-sm mb-2',
    amount: 'text-4xl font-bold mb-4',
    dateRow: 'flex items-center gap-2 text-indigo-400 font-medium',
    calendarIcon: Calendar,
    calendarIconSize: 'w-4 h-4',
  },
  planCard: {
    base: 'lg:col-span-2 glass-card p-8 rounded-3xl flex items-center justify-between',
    label: 'text-slate-400 text-sm mb-2',
    planName: 'text-2xl font-semibold',
    manageButton: 'px-6 py-3 bg-white/5 hover:bg-white/10 rounded-xl transition-colors font-medium',
  },
  historyCard: {
    base: 'glass-card rounded-3xl overflow-hidden',
    header: 'p-6 border-b border-white/5',
    headerTitle: 'font-medium',
    tableWrapper: 'overflow-x-auto',
    table: 'w-full text-left',
    thead: 'text-slate-500 text-xs uppercase tracking-widest border-b border-white/5',
    th: 'px-8 py-4 font-semibold',
    thRight: 'px-8 py-4 font-semibold text-right',
    tbody: 'divide-y divide-white/5',
    tr: 'hover:bg-white/5 transition-colors',
    td: 'px-8 py-4',
    tdMuted: 'px-8 py-4 text-slate-400',
    tdRight: 'px-8 py-4 text-right',
    statusBadge: 'px-3 py-1 bg-emerald-500/10 text-emerald-400 text-[10px] font-bold rounded-full uppercase tracking-widest',
    downloadButton: 'p-2 hover:bg-white/10 rounded-lg transition-colors text-indigo-400',
    downloadIcon: Download,
    downloadIconSize: 'w-4 h-4',
  },
  text: {
    title: 'Your Plan',
    nextPaymentLabel: 'Next Payment Due',
    nextPaymentAmount: '£249.00',
    nextPaymentDate: 'April 15, 2026',
    currentPlanLabel: 'Current Plan',
    currentPlanName: 'Premium Enterprise',
    managePlan: 'Manage Plan',
    paymentHistoryTitle: 'Payment History',
    tableHeaders: ['Invoice', 'Date', 'Amount', 'Status', 'Action'],
  },
  invoices: [
    { id: 'INV-001', date: 'Mar 15, 2026', amount: '£249.00', status: 'Paid' },
    { id: 'INV-002', date: 'Feb 15, 2026', amount: '£249.00', status: 'Paid' },
    { id: 'INV-003', date: 'Jan 15, 2026', amount: '£249.00', status: 'Paid' },
  ],
};
