import { ArrowLeft, UserPlus, ExternalLink, FileText } from 'lucide-react';

export const clientManagementViewUI = {
  page: {
    motionKey: 'client-management',
    animation: {
      initial: { opacity: 0, y: 20 },
      animate: { opacity: 1, y: 0 },
    },
    padding: 'p-8',
    maxWidth: 'max-w-[1600px] mx-auto w-full space-y-10',
  },
  header: {
    layout: 'flex flex-col md:flex-row md:items-center justify-between gap-6 mb-12',
    titleStyle: 'text-4xl font-black tracking-tight text-[var(--client-widget-text)]',
    title: 'Revenue Command',
    subtitleStyle: 'text-dim text-sm mt-1 font-medium',
    subtitle: 'High-fidelity lifecycle management for your client portfolio.',
    backButton: {
      targetView: 'agency-clients',
      layout: 'flex items-center gap-2 px-6 py-3 premium-glass text-[10px] font-black uppercase tracking-widest text-[var(--client-widget-text)] hover:glow-primary transition-all active:scale-95',
      icon: ArrowLeft,
      iconSize: 'w-4 h-4',
      label: 'Portfolio Overview',
    },
  },
  mainGrid: {
    layout: 'grid grid-cols-1 lg:grid-cols-12 gap-10',
  },
  clientList: {
    container: 'lg:col-span-4 space-y-4',
    listContainer: 'premium-glass overflow-hidden divide-y divide-[var(--client-widget-border)]',
    clientButton: {
      base: 'w-full text-left px-6 py-5 transition-all relative group overflow-hidden',
      active: 'bg-[var(--client-widget-primary-color-1)]/10 text-[var(--client-widget-primary-color-1)] glow-primary z-10',
      inactive: 'hover:bg-white/5 text-dim hover:text-[var(--client-widget-text)]',
      nameStyle: 'text-base font-black tracking-tight group-hover:translate-x-1 transition-transform',
      stageStyle: 'text-[9px] font-black uppercase tracking-widest opacity-60 mt-1',
    },
    addClientButton: {
      layout: 'w-full flex items-center justify-center gap-3 px-6 py-4 premium-glass border-dashed text-xs font-black uppercase tracking-widest text-dim hover:text-[var(--client-widget-primary-color-1)] hover:border-[var(--client-widget-primary-color-1)]/30 hover:glow-primary transition-all',
      icon: UserPlus,
      iconSize: 'w-5 h-5',
      label: 'Onboard New Client',
    },
  },
  detailsPane: {
    container: 'lg:col-span-8',
    contentContainer: 'space-y-8',
    card: 'premium-glass p-10 relative overflow-hidden',
    header: {
      layout: 'flex items-center justify-between mb-10',
      titleStyle: 'text-3xl font-black text-[var(--client-widget-text)] tracking-tight',
      titlePrefix: '',
      impersonateButton: {
        layout: 'flex items-center gap-3 px-8 py-4 rounded-2xl bg-[var(--client-widget-primary-color-1)] text-white text-xs font-black uppercase tracking-[0.2em] shadow-2xl hover:brightness-110 active:scale-95 transition-all glow-primary',
        icon: ExternalLink,
        iconSize: 'w-5 h-5',
        label: 'Deliver Experience',
      },
    },
    grid: 'grid grid-cols-1 md:grid-cols-2 gap-12',
    leftCol: 'space-y-10',
    rightCol: 'space-y-10',
    stageSelector: {
      labelStyle: 'text-[10px] font-black text-dim uppercase tracking-[0.2em] mb-4 block',
      label: 'Lifecycle Stage',
      container: 'flex flex-wrap gap-2.5',
      stages: ['discovery', 'design', 'development', 'live'] as const,
      button: {
        base: 'px-6 py-2.5 rounded-xl text-[10px] font-black uppercase tracking-widest transition-all border border-transparent',
        active: 'bg-[var(--client-widget-primary-color-1)] text-white shadow-xl glow-primary',
        inactive: 'bg-white/5 text-dim border-white/5 hover:bg-white/10 hover:text-[var(--client-widget-text)]',
      },
    },
    discoveryStatus: {
      labelStyle: 'text-[10px] font-black text-dim uppercase tracking-[0.2em] mb-4 block',
      label: 'Discovery Intensity',
      card: 'premium-glass p-6 border-white/5',
      header: 'flex items-center justify-between mb-4',
      titleStyle: 'text-xs font-black text-[var(--client-widget-text)] uppercase tracking-tight',
      title: 'Global Knowledge Base',
      countStyle: 'text-sm font-black text-[var(--client-widget-primary-color-1)]',
      progressContainer: 'h-2 w-full bg-white/5 rounded-full overflow-hidden p-0.5',
      progressBar: 'h-full bg-gradient-to-r from-[var(--client-widget-primary-color-1)] to-indigo-400 rounded-full transition-all duration-1000 glow-primary',
    },
    resources: {
      header: 'flex items-center justify-between mb-4',
      labelStyle: 'text-[10px] font-black text-dim uppercase tracking-[0.2em] block',
      label: 'Shared Assets',
      uploadButton: 'text-[10px] font-black text-[var(--client-widget-primary-color-1)] uppercase tracking-widest hover:glow-primary transition-all',
      uploadLabel: 'Add Asset',
      uploadPrompt: 'Asset Identifier:',
      listContainer: 'space-y-3 mt-4',
      emptyStyle: 'text-xs text-dim italic',
      emptyText: 'No shared assets present in this silo.',
      item: {
        layout: 'flex items-center justify-between px-5 py-3 premium-glass border-white/5 hover:border-[var(--client-widget-primary-color-1)]/20 transition-all group/asset',
        nameStyle: 'text-sm font-bold text-[var(--client-widget-text)] group-hover:text-[var(--client-widget-primary-color-1)] transition-colors',
        icon: FileText,
        iconSize: 'w-4 h-4 text-dim group-hover:text-[var(--client-widget-primary-color-1)]',
      },
    },
    assignedEmployees: {
      labelStyle: 'text-[10px] font-black text-dim uppercase tracking-[0.2em] mb-4 block',
      label: 'Strategic Alignment Team',
      listContainer: 'grid grid-cols-1 gap-3',
      item: {
        layout: 'flex items-center gap-4 cursor-pointer group p-4 rounded-2xl border border-transparent hover:bg-white/5 transition-all',
        checkbox: 'w-5 h-5 rounded-lg border-white/10 bg-white/5 text-[var(--client-widget-primary-color-1)] focus:ring-[var(--client-widget-primary-color-1)] focus:ring-offset-0',
        avatarContainer: 'flex items-center gap-3',
        avatar: 'w-10 h-10 rounded-2xl bg-gradient-to-br from-[var(--client-widget-primary-color-1)]/20 to-transparent text-[var(--client-widget-primary-color-1)] text-sm flex items-center justify-center font-black group-hover:glow-primary transition-all',
        nameStyle: 'text-sm font-bold text-dim group-hover:text-[var(--client-widget-text)] transition-colors',
      },
    },
  },
  emptyState: {
    container: 'premium-glass p-20 flex flex-col items-center justify-center text-center space-y-6',
    icon: UserPlus,
    iconSize: 'w-16 h-16 text-dim opacity-20',
    titleStyle: 'text-2xl font-black text-[var(--client-widget-text)] tracking-tight',
    title: 'Select Strategic Account',
    subtitleStyle: 'text-sm text-dim max-w-sm',
    subtitle: 'Access high-fidelity lifecycle management by choosing a client from your portfolio.',
  },
};
