import { Plus, Trash2, Edit2, Shield, Save } from 'lucide-react';

export const roleBuilderUI = {
  card: 'glass-card p-5 md:p-8 rounded-2xl md:rounded-3xl',
  header: {
    base: 'flex flex-col md:flex-row md:items-center justify-between gap-6 mb-6 md:mb-8',
    titleStyle: 'text-xl md:text-2xl font-semibold flex items-center gap-3',
    icon: Shield,
    iconSize: 'w-5 h-5 md:w-6 md:h-6 text-[var(--color-primary)]',
    actions: 'flex gap-3',
    cancelButton: 'flex-1 md:flex-none px-4 py-2 bg-white/5 hover:bg-white/10 rounded-xl transition-colors text-xs md:text-sm',
    saveButton: 'flex-1 md:flex-none px-4 py-2 bg-[var(--color-primary)] hover:brightness-110 rounded-xl transition-colors flex items-center justify-center gap-2 text-xs md:text-sm',
    createButton: 'w-full md:w-auto px-4 py-2 bg-[var(--color-primary)] hover:brightness-110 rounded-xl transition-colors flex items-center justify-center gap-2 text-xs md:text-sm',
    saveIcon: Save,
    createIcon: Plus,
    buttonIconSize: 'w-3.5 h-3.5 md:w-4 md:h-4',
  },
  text: {
    listTitle: 'Roles & Permissions',
    editTitlePrefix: 'Edit Role:',
    roleNameLabel: 'Role Name',
    standardPermissionsTitle: 'Standard Permissions',
    customPermissionsTitle: 'Custom Page Permissions',
    cancelText: 'Cancel',
    saveText: 'Save Role',
    createText: 'Create Role',
    noRoles: 'No custom roles created yet.',
  },
  editForm: {
    nameSection: 'mb-6 md:mb-8',
    label: 'text-[10px] md:text-xs uppercase tracking-widest text-slate-500 mb-2 block',
    input: 'w-full max-w-md bg-slate-900/50 border border-white/10 rounded-xl p-2.5 md:p-3 text-xs md:text-sm text-white focus:outline-none focus:border-[var(--color-primary)]',
    permissionsSection: 'space-y-6 md:space-y-8',
    permissionGroupTitle: 'text-base md:text-lg font-medium mb-4',
    permissionsGrid: 'grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3 md:gap-4',
    permissionItem: 'flex items-center gap-3 p-3 md:p-4 bg-white/5 rounded-xl cursor-pointer hover:bg-white/10 transition-colors border border-white/5',
    checkbox: 'w-4 h-4 rounded border-white/20 bg-slate-900 text-[var(--color-primary)] focus:ring-[var(--color-primary)] focus:ring-offset-slate-900',
    checkboxLabel: 'text-xs md:text-sm font-medium',
  },
  roleList: 'space-y-3 md:space-y-4',
  roleEmpty: 'text-center py-10 text-slate-500 border border-dashed border-white/10 rounded-xl md:rounded-2xl text-sm',
  roleRow: {
    base: 'flex items-center justify-between p-3 md:p-4 bg-white/5 rounded-xl md:rounded-2xl border border-white/5 hover:border-white/10 transition-colors',
    info: 'min-w-0',
    name: 'font-medium text-white flex items-center gap-2 text-sm md:text-base truncate',
    systemBadge: 'px-2 py-0.5 bg-[var(--color-primary)]/20 text-[var(--color-primary)] text-[8px] md:text-[10px] uppercase tracking-widest rounded-full font-bold shrink-0',
    detail: 'text-[10px] md:text-xs text-slate-500 mt-1',
    actions: 'flex items-center gap-1 md:gap-2 shrink-0',
    editButton: 'p-2 text-slate-400 hover:text-white hover:bg-white/5 rounded-lg transition-colors',
    editIcon: Edit2,
    deleteButton: 'p-2 text-red-400 hover:bg-red-400/10 rounded-lg transition-colors',
    deleteIcon: Trash2,
    iconSize: 'w-3.5 h-3.5 md:w-4 md:h-4',
  },
  standardViews: [
    { id: 'dashboard', label: 'Dashboard' },
    { id: 'agency-clients', label: 'Clients' },
    { id: 'project-hub', label: 'Projects' },
    { id: 'inbox', label: 'Inbox' },
    { id: 'employee-management', label: 'Team' },
    { id: 'global-activity', label: 'Activity Logs' },
    { id: 'ai-sessions', label: 'AI Monitor' },
    { id: 'agency-builder', label: 'App Builder' },
  ],
};
