import { X, CheckSquare, ChevronUp, ChevronDown, Edit2, Trash2, Plus, Layers, Check } from 'lucide-react';

export const globalTasksModalUI = {
  overlay: 'fixed inset-0 z-50 flex justify-end',
  backdrop: {
    motion: { initial: { opacity: 0 }, animate: { opacity: 1 }, exit: { opacity: 0 } },
    className: 'absolute inset-0',
  },
  panel: {
    animation: {
      initial: { x: '100%' },
      animate: { x: 0 },
      exit: { x: '100%' },
      transition: { type: 'spring' as const, damping: 25, stiffness: 200 },
    },
    base: 'relative w-full sm:max-w-md h-full bg-slate-900 border-l border-white/10 shadow-2xl flex flex-col',
  },
  header: {
    base: 'flex items-center justify-between px-4 sm:px-6 py-3 sm:py-4 border-b border-white/10 bg-black/20 shrink-0',
    titleStyle: 'text-lg sm:text-xl font-semibold text-white',
    title: 'Task Center',
    closeButton: 'p-2 text-slate-400 hover:text-white hover:bg-white/10 rounded-xl transition-colors',
    closeIcon: X,
    closeIconSize: 'w-5 h-5',
  },
  tabs: {
    base: 'flex border-b border-white/10 bg-black/10 shrink-0',
    iconClass: 'w-4 h-4',
    button: {
      base: 'flex-1 flex items-center justify-center gap-2 py-3 text-sm font-medium transition-colors border-b-2',
      active: 'border-indigo-500 text-indigo-400',
      inactive: 'border-transparent text-slate-400 hover:text-white hover:bg-white/5',
    },
    personal: { icon: CheckSquare, label: 'Personal' },
    project: { icon: Layers, label: 'Projects' },
  },
  content: {
    base: 'flex-1 overflow-y-auto custom-scrollbar p-4 sm:p-6',
    section: 'space-y-3',
    header: 'flex items-center justify-between mb-3',
    title: 'text-sm font-semibold text-slate-300',
    addButton: 'w-7 h-7 rounded-lg bg-indigo-600 text-white flex items-center justify-center hover:bg-indigo-500 transition-colors',
    addIcon: Plus,
    addIconSize: 'w-4 h-4',
  },
  todoItem: {
    base: 'flex items-center gap-2 sm:gap-3 p-3 sm:p-4 bg-white/5 rounded-xl sm:rounded-2xl border border-white/5 hover:border-white/10 transition-all group',
    textContainer: 'flex-1 min-w-0',
    editContainer: 'flex items-center gap-2',
    editInput: 'flex-1 bg-white/10 border border-white/20 rounded-lg px-3 py-1.5 text-sm outline-none focus:border-indigo-500 transition-all',
    saveButton: 'text-xs text-indigo-400 font-medium hover:text-indigo-300 transition-colors',
    text: 'text-sm font-medium truncate',
    textCompleted: 'line-through text-slate-500',
    textIncomplete: 'text-slate-200',
    tagsContainer: 'flex gap-2 mt-1.5 sm:mt-2',
    priorityBadge: 'text-[8px] sm:text-[9px] px-2 py-0.5 rounded-full font-bold uppercase tracking-widest',
    priorityHigh: 'bg-red-500/10 text-red-400',
    priorityMedium: 'bg-amber-500/10 text-amber-400',
    priorityLow: 'bg-indigo-500/10 text-indigo-400',
    moveButtons: {
      base: 'flex flex-col gap-0.5',
      button: 'p-0.5 text-slate-600 hover:text-slate-300 transition-colors disabled:opacity-30',
      upIcon: ChevronUp,
      downIcon: ChevronDown,
      iconSize: 'w-3.5 h-3.5',
    },
    checkbox: 'w-4 h-4 sm:w-5 sm:h-5 rounded-md border-2 flex items-center justify-center transition-all shrink-0',
    checkboxCompleted: 'bg-indigo-600 border-indigo-600',
    checkboxIncomplete: 'border-white/20 hover:border-indigo-500',
    checkIcon: Check,
    checkIconSize: 'w-2.5 h-2.5 sm:w-3 sm:h-3 text-white',
    actions: {
      base: 'flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity',
      button: 'p-1.5 hover:bg-white/10 rounded-lg transition-colors',
      editIcon: Edit2,
      deleteIcon: Trash2,
      iconSize: 'w-3.5 h-3.5 text-slate-400',
    },
  },
  projectTaskItem: {
    base: 'p-3 sm:p-4 bg-white/5 rounded-xl sm:rounded-2xl border border-white/5',
    headerRow: 'flex justify-between items-start mb-1.5 sm:mb-2',
    title: 'text-sm font-medium text-white',
    description: 'text-xs text-slate-500',
    statusBadge: 'text-[8px] sm:text-[9px] px-2 py-0.5 rounded-full font-bold uppercase tracking-widest shrink-0',
    statusDone: 'bg-emerald-500/10 text-emerald-400',
    statusInProgress: 'bg-indigo-500/10 text-indigo-400',
    statusDefault: 'bg-slate-500/10 text-slate-400',
  },
  text: {
    personalTodosTitle: 'Personal Todos',
    projectTasksTitle: 'Project Tasks',
    addTaskPrompt: 'Task description:',
    saveText: 'Save',
    newTodoDefaults: { priority: 'Medium' as const, category: 'General', completed: false },
  },
};
