import { ArrowLeft, UserPlus, ExternalLink, FileText } from 'lucide-react';

export const clientManagementViewUI = {
  page: {
    motionKey: 'client-management',
    animation: {
      initial: { opacity: 0, y: 20 },
      animate: { opacity: 1, y: 0 },
    },
    padding: 'p-4 md:p-8',
    maxWidth: 'max-w-7xl mx-auto w-full',
  },
  header: {
    layout: 'flex items-center justify-between mb-8',
    titleStyle: 'text-2xl font-bold tracking-tight',
    title: 'Client Management',
    subtitleStyle: 'text-slate-400 text-sm mt-1',
    subtitle: 'Manage client accounts, stages, and portal access.',
    backButton: {
      targetView: 'agency-clients',
      layout: 'flex items-center gap-2 px-4 py-2 bg-white/5 border border-white/10 rounded-xl text-sm text-slate-300 hover:bg-white/10 transition-all',
      icon: ArrowLeft,
      iconSize: 'w-4 h-4',
      label: 'Back to Clients',
    },
  },
  mainGrid: {
    layout: 'grid grid-cols-1 lg:grid-cols-3 gap-6',
  },
  clientList: {
    container: 'lg:col-span-1',
    listContainer: 'glass-card rounded-2xl border border-white/5 overflow-hidden mb-4 divide-y divide-white/5',
    clientButton: {
      base: 'w-full text-left px-5 py-4 transition-all',
      active: 'bg-[var(--color-primary)]/10 text-[var(--color-primary)]',
      inactive: 'hover:bg-white/5 text-slate-300',
      nameStyle: 'text-sm font-semibold',
      stageStyle: 'text-xs text-slate-500 capitalize mt-0.5',
    },
    addClientButton: {
      layout: 'w-full flex items-center justify-center gap-2 px-4 py-3 glass-card rounded-2xl border border-white/5 text-sm text-slate-400 hover:text-white hover:bg-white/5 transition-all',
      icon: UserPlus,
      iconSize: 'w-4 h-4',
      label: 'Add Client',
    },
  },
  detailsPane: {
    container: 'lg:col-span-2',
    contentContainer: '',
    card: 'glass-card rounded-2xl border border-white/5 p-6 md:p-8',
    header: {
      layout: 'flex items-center justify-between mb-6',
      titleStyle: 'text-lg font-bold text-slate-100',
      titlePrefix: '',
      impersonateButton: {
        layout: 'flex items-center gap-2 px-4 py-2 rounded-xl text-sm font-semibold text-white transition-all hover:opacity-90',
        icon: ExternalLink,
        iconSize: 'w-4 h-4',
        label: 'View Portal',
      },
    },
    grid: 'grid grid-cols-1 md:grid-cols-2 gap-6',
    leftCol: 'space-y-6',
    rightCol: 'space-y-6',
    stageSelector: {
      labelStyle: 'text-xs font-semibold text-slate-400 uppercase tracking-widest mb-2 block',
      label: 'Project Stage',
      container: 'flex flex-wrap gap-2',
      stages: ['discovery', 'design', 'development', 'live'] as const,
      button: {
        base: 'px-3 py-1.5 rounded-lg text-xs font-semibold capitalize transition-all',
        active: 'bg-[var(--color-primary)] text-white shadow-lg',
        inactive: 'bg-white/5 text-slate-400 hover:bg-white/10',
      },
    },
    permissions: {
      labelStyle: 'text-xs font-semibold text-slate-400 uppercase tracking-widest mb-2 block',
      label: 'Portal Permissions',
      grid: 'grid grid-cols-2 gap-2',
      list: ['dashboard', 'onboarding', 'support', 'resources', 'crm', 'website', 'collaboration', 'discover', 'aqua-ai', 'feature-request'],
      item: {
        layout: 'flex items-center gap-2 cursor-pointer group',
        checkbox: 'rounded border-white/20 bg-white/5 text-[var(--color-primary)] focus:ring-[var(--color-primary)]',
        labelStyle: 'text-sm text-slate-400 group-hover:text-slate-300 capitalize transition-colors',
      },
    },
    discoveryStatus: {
      labelStyle: 'text-xs font-semibold text-slate-400 uppercase tracking-widest mb-2 block',
      label: 'Discovery Progress',
      card: 'bg-white/5 rounded-xl p-4',
      header: 'flex items-center justify-between mb-3',
      titleStyle: 'text-sm font-medium text-slate-300',
      title: 'Questions Answered',
      countStyle: 'text-sm font-bold text-[var(--color-primary)]',
      progressContainer: 'h-1.5 w-full bg-white/10 rounded-full overflow-hidden',
      progressBar: 'h-full bg-[var(--color-primary)] rounded-full transition-all',
    },
    resources: {
      header: 'flex items-center justify-between mb-2',
      labelStyle: 'text-xs font-semibold text-slate-400 uppercase tracking-widest block',
      label: 'Resources',
      uploadButton: 'text-xs text-[var(--color-primary)] hover:text-[var(--color-primary)] transition-colors',
      uploadLabel: '+ Upload',
      uploadPrompt: 'Enter resource name:',
      listContainer: 'space-y-2 mt-2',
      emptyStyle: 'text-sm text-slate-600',
      emptyText: 'No resources uploaded yet.',
      item: {
        layout: 'flex items-center justify-between px-3 py-2 bg-white/5 rounded-lg',
        nameStyle: 'text-sm text-slate-300',
        icon: FileText,
        iconSize: 'w-4 h-4 text-slate-500',
      },
    },
    assignedEmployees: {
      labelStyle: 'text-xs font-semibold text-slate-400 uppercase tracking-widest mb-2 block',
      label: 'Assigned Team',
      listContainer: 'space-y-2 mt-2',
      item: {
        layout: 'flex items-center gap-3 cursor-pointer group',
        checkbox: 'rounded border-white/20 bg-white/5 text-[var(--color-primary)] focus:ring-[var(--color-primary)]',
        avatarContainer: 'flex items-center gap-2',
        avatar: 'w-7 h-7 rounded-full bg-[var(--color-primary)]/20 text-[var(--color-primary)] text-xs flex items-center justify-center font-bold',
        nameStyle: 'text-sm text-slate-400 group-hover:text-slate-300 transition-colors',
      },
    },
  },
  emptyState: {
    container: 'glass-card rounded-2xl border border-white/5 p-12 flex flex-col items-center justify-center text-center',
    icon: UserPlus,
    iconSize: 'w-12 h-12 text-slate-600 mb-4',
    titleStyle: 'text-lg font-semibold text-slate-300 mb-2',
    title: 'Select a Client',
    subtitleStyle: 'text-sm text-slate-500',
    subtitle: 'Choose a client from the list to manage their account and portal access.',
  },
};
