// Promote-to-repo orchestrator (D-3).
//
// Reads the currently-published overrides for a site, serialises them into
// the canonical portal.overrides.json shape, and opens a PR against the
// repo configured in admin settings. The host site can import the JSON
// at build time so the rendered HTML always reflects the last-published
// state — runtime override fetching still works on top, but the SSR
// snapshot is now durable and SEO-friendly.
//
// We commit a single file at the repo root (path configurable). One PR
// per call; if a PR already exists for the head branch we return the
// existing one instead of creating a duplicate.

import { getContentState } from "./content";
import { openPullRequest, parseRepoUrl, type OpenPullRequestResult } from "./github";

export interface PromoteInput {
  siteId: string;
  repoUrl: string;
  baseBranch?: string;             // default "main"
  pat: string;                     // GitHub Personal Access Token
  filePath?: string;               // default "portal.overrides.json"
  message?: string;                // optional admin-written commit msg
  prefix?: string;                 // branch prefix; default "portal/sync"
}

export interface PromoteResult extends OpenPullRequestResult {
  filePath?: string;
  fileContent?: string;            // useful for the UI to show a diff later
}

export async function promoteSiteToRepo(input: PromoteInput): Promise<PromoteResult> {
  const repo = parseRepoUrl(input.repoUrl);
  if (!repo) return { ok: false, error: "Invalid GitHub repo URL" };
  if (!input.pat) return { ok: false, error: "Missing GitHub PAT" };

  const state = getContentState(input.siteId);
  if (Object.keys(state.published).length === 0) {
    return { ok: false, error: "Nothing published yet — Publish first, then Promote." };
  }

  const filePath = input.filePath ?? "portal.overrides.json";
  const baseBranch = input.baseBranch ?? "main";
  const prefix = (input.prefix ?? "portal/sync").replace(/\/$/, "");
  // Stable branch name per site so repeated promotes update the same PR
  // rather than spawning a new branch on every push. The day stamp keeps
  // it human-readable when re-opened weeks later.
  const stamp = new Date().toISOString().slice(0, 10);
  const headBranch = `${prefix}/${input.siteId}-${stamp}`;

  const fileContent = serialisePublishedState(input.siteId, state.published, state.history[0]?.publishedAt);

  const summary = describeChanges(state.published);
  const commitMessage = input.message
    ? `chore(portal): sync ${input.siteId} content (${summary})\n\n${input.message}`
    : `chore(portal): sync ${input.siteId} content (${summary})`;
  const prTitle = `Portal: sync ${input.siteId} content (${summary})`;
  const prBody = renderPrBody(input.siteId, state.published, state.history[0]?.message);

  return await openPullRequest({
    repoUrl: input.repoUrl,
    baseBranch,
    headBranch,
    files: [{ path: filePath, content: fileContent }],
    commitMessage,
    prTitle,
    prBody,
    auth: { pat: input.pat },
  }).then(r => ({ ...r, filePath, fileContent }));
}

// Serialise the published overrides into the canonical portal.overrides.json
// shape. Keys are sorted alphabetically so the diff is stable across runs.
function serialisePublishedState(
  siteId: string,
  published: Record<string, { value: string; type: string; updatedAt: number }>,
  publishedAt?: number,
): string {
  const sortedKeys = Object.keys(published).sort();
  const overrides: Record<string, { value: string; type: string }> = {};
  for (const k of sortedKeys) {
    const o = published[k];
    overrides[k] = { value: o.value, type: o.type };
  }
  const doc = {
    $schema: "https://schemas.portal.dev/portal-overrides.v1.json",
    siteId,
    publishedAt: publishedAt ?? Date.now(),
    overrides,
  };
  return JSON.stringify(doc, null, 2) + "\n";
}

function describeChanges(published: Record<string, unknown>): string {
  const n = Object.keys(published).length;
  return n === 1 ? "1 key" : `${n} keys`;
}

function renderPrBody(
  siteId: string,
  published: Record<string, { value: string; type: string }>,
  lastNote?: string,
): string {
  const keys = Object.keys(published).sort();
  const top = keys.slice(0, 12);
  const more = keys.length - top.length;

  const lines: string[] = [];
  lines.push(`Site: \`${siteId}\``);
  lines.push("");
  lines.push("Auto-generated by the portal admin. Merging this PR commits the");
  lines.push("currently-published content overrides into the repo so the next");
  lines.push("build picks them up at SSR time.");
  lines.push("");
  if (lastNote) {
    lines.push(`> ${lastNote.replace(/\n/g, "\n> ")}`);
    lines.push("");
  }
  lines.push("**Keys included (" + keys.length + "):**");
  for (const k of top) lines.push(`- \`${k}\` *(${published[k].type})*`);
  if (more > 0) lines.push(`- …and ${more} more`);
  lines.push("");
  lines.push("---");
  lines.push("This file lives at `portal.overrides.json` at the repo root. The");
  lines.push("portal client reads it at build time — see `src/portal/client/index.ts`.");
  return lines.join("\n");
}
