import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const PROJECT_ROOT = path.resolve(__dirname, '..');
const APPSHELL_ROOT = path.join(PROJECT_ROOT, 'AppShell');
const TEMPLATES_ROOT = path.resolve(PROJECT_ROOT, '..', 'Templates');

const SEARCH_DIRS = [
  path.join(APPSHELL_ROOT, 'components'),
  path.join(APPSHELL_ROOT, 'AppFrame'),
  path.join(APPSHELL_ROOT, 'TopBar'),
  path.join(APPSHELL_ROOT, 'Sidebar'),
  path.join(APPSHELL_ROOT, 'Renderer'),
  path.join(TEMPLATES_ROOT, 'AQUA Client')
];
const OUTPUT_FILE = path.join(APPSHELL_ROOT, 'components', 'autoComponentMap.ts');

const MANUAL_MAPPINGS = {
  'dashboard': 'DashboardOverviewView',
  'welcome-screen': 'WelcomeScreen',
  'login-view': 'LoginView',
  'security-check': 'SecurityCheckView',
  'bridge-control': 'BridgeControlView',
};

function kebabCase(str) {
  return str
    .replace(/([A-Z])/g, '-$1')
    .toLowerCase()
    .replace(/^-/, '')
    .replace(/-widget$/, '')
    .replace(/-view$/, '');
}

function findComponents(dir, components = []) {
  if (!fs.existsSync(dir)) return components;
  if (dir.includes('node_modules')) return components; // SKIP NODE_MODULES
  
  const files = fs.readdirSync(dir);
  for (const file of files) {
    const fullPath = path.join(dir, file);
    const stat = fs.statSync(fullPath);
    
    if (stat.isDirectory()) {
      findComponents(fullPath, components);
    } else if (file.endsWith('.tsx') && !file.endsWith('.demo.tsx') && !file.includes('registry') && file !== 'SmartRegistry.tsx' && !file.includes('autoComponentMap')) {
      const content = fs.readFileSync(fullPath, 'utf8');
      
      const defaultExportMatch = content.match(/export default\s+(?:async\s+)?(?:function\s+)?([A-Z]\w+)/) || 
                                 content.match(/export default\s+([A-Z]\w+)/);
      
      const namedExportMatches = Array.from(content.matchAll(/export\s+(?:async\s+)?(?:const|function|let|var)\s+([A-Z]\w+)/g));
      
      if (defaultExportMatch) {
        const name = defaultExportMatch[1];
        addComponent(components, name, fullPath, true, false);
      }
      
      for (const match of namedExportMatches) {
        const name = match[1];
        if (/^[A-Z]/.test(file) || name === path.basename(file, '.tsx') || name.endsWith('Widget') || name.endsWith('View') || name === 'AgencySetupView' || name === 'DesignModeInspector') {
          addComponent(components, name, fullPath, false, true);
        }
      }
    }
  }
  return components;
}

function addComponent(components, name, fullPath, isDefault, isNamed) {
  let importPath = '';
  if (fullPath.startsWith(APPSHELL_ROOT)) {
    importPath = '@/AppShell' + fullPath.substring(APPSHELL_ROOT.length);
  } else if (fullPath.startsWith(TEMPLATES_ROOT)) {
    importPath = '@/Templates' + fullPath.substring(TEMPLATES_ROOT.length);
  }

  importPath = importPath.split(path.sep).join('/');
  importPath = importPath.replace(/\.tsx$/, '');

  components.push({
    name,
    path: importPath,
    isDefaultExport: isDefault,
    isNamedExport: isNamed
  });
}

console.log('Scanning for components...');
const components = [];
SEARCH_DIRS.forEach(dir => findComponents(dir, components));

const seen = new Set();
const uniqueComponents = components.filter(c => {
  if (seen.has(c.name)) return false;
  seen.add(c.name);
  return true;
});

console.log(`Found ${uniqueComponents.length} components.`);

let output = `/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * AUTO-GENERATED COMPONENT MAP
 * Generated by scripts/generateRegistry.js
 * DO NOT EDIT MANUALLY
 */

import type { ComponentType } from 'react';
import dynamic from 'next/dynamic';

`;

uniqueComponents.forEach(c => {
  if (c.isNamedExport) {
    output += `const ${c.name} = dynamic(() => import('${c.path}').then(mod => mod.${c.name} as ComponentType<any>));\n`;
  } else {
    output += `const ${c.name} = dynamic(() => import('${c.path}') as Promise<{ default: ComponentType<any> }>);\n`;
  }
});

output += `\nexport const autoComponentMap: Record<string, ComponentType<any>> = {\n`;

const uniqueKebabKeys = new Set(Object.keys(MANUAL_MAPPINGS));
uniqueComponents.forEach(c => {
  output += `  ${c.name},\n`;
  uniqueKebabKeys.add(c.name);
  
  const kebab = kebabCase(c.name);
  if (kebab !== c.name.toLowerCase() && kebab !== c.name && !uniqueKebabKeys.has(kebab)) {
    output += `  '${kebab}': ${c.name},\n`;
    uniqueKebabKeys.add(kebab);
  }
});

output += `\n  // Manual Mappings\n`;
Object.entries(MANUAL_MAPPINGS).forEach(([key, componentName]) => {
  if (seen.has(componentName)) {
    output += `  '${key}': ${componentName},\n`;
  }
});

output += `};\n\nexport type WidgetName = string;\nexport type ViewName = string;\n`;

fs.writeFileSync(OUTPUT_FILE, output);
console.log(`Successfully generated ${OUTPUT_FILE}`);
