/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * AUTO-GENERATED COMPONENT MAP
 * Generated by scripts/generateRegistry.js
 * DO NOT EDIT MANUALLY
 */

import type { ComponentType } from 'react';
import dynamic from 'next/dynamic';

const LoginView = dynamic(() => import('@ClientShell/components/Auth/ClientLoginView').then(mod => mod.LoginView as ComponentType<any>));
const SecurityCheckView = dynamic(() => import('@ClientShell/components/Auth/ClientSecurityCheckView').then(mod => mod.SecurityCheckView as ComponentType<any>));
const WelcomeScreen = dynamic(() => import('@ClientShell/components/Auth/ClientWelcomeScreen').then(mod => mod.WelcomeScreen as ComponentType<any>));
const BridgeControlView = dynamic(() => import('@ClientShell/components/BridgeControl/ClientBridgeControlView').then(mod => mod.BridgeControlView as ComponentType<any>));
const ModalManager = dynamic(() => import('@ClientShell/components/ClientModalManager').then(mod => mod.ModalManager as ComponentType<any>));
const GlobalTasksModal = dynamic(() => import('@ClientShell/components/Modals/ClientGlobalTasksModal').then(mod => mod.GlobalTasksModal as ComponentType<any>));
const InboxModal = dynamic(() => import('@ClientShell/components/Modals/ClientInboxModal').then(mod => mod.InboxModal as ComponentType<any>));
const NotificationsModal = dynamic(() => import('@ClientShell/components/Modals/ClientNotificationsModal').then(mod => mod.NotificationsModal as ComponentType<any>));
const AgencyConfiguratorView = dynamic(() => import('@ClientShell/components/Settings/ClientSettingsPlaceholder').then(mod => mod.AgencyConfiguratorView as ComponentType<any>));
const GlobalSettingsView = dynamic(() => import('@ClientShell/components/Settings/ClientSettingsPlaceholder').then(mod => mod.GlobalSettingsView as ComponentType<any>));
const IntegrationsView = dynamic(() => import('@ClientShell/components/Settings/ClientSettingsPlaceholder').then(mod => mod.IntegrationsView as ComponentType<any>));
const AgencyBuilderView = dynamic(() => import('@ClientShell/components/Settings/ClientSettingsPlaceholder').then(mod => mod.AgencyBuilderView as ComponentType<any>));
const AllUsersView = dynamic(() => import('@ClientShell/components/Settings/ClientSettingsPlaceholder').then(mod => mod.AllUsersView as ComponentType<any>));
const DashboardView = dynamic(() => import('@ClientShell/components/Settings/ClientSettingsPlaceholder').then(mod => mod.DashboardView as ComponentType<any>));
const EditableText = dynamic(() => import('@ClientShell/components/design/ClientEditableText').then(mod => mod.EditableText as ComponentType<any>));
const SubNavBar = dynamic(() => import('@ClientShell/components/shared/ClientSubNavBar').then(mod => mod.SubNavBar as ComponentType<any>));
const ClientTopBar = dynamic(() => import('@ClientShell/components/shared/ClientTopBar').then(mod => mod.ClientTopBar as ComponentType<any>));
const AppFrame = dynamic(() => import('@ClientShell/AppFrame/ClientAppFrame').then(mod => mod.AppFrame as ComponentType<any>));
const ClientSidebarContent = dynamic(() => import('@ClientShell/Sidebar/ClientSidebarContent').then(mod => mod.ClientSidebarContent as ComponentType<any>));
const Search = dynamic(() => import('@ClientShell/Sidebar/components/ClientSearch').then(mod => mod.Search as ComponentType<any>));
const SidebarItem = dynamic(() => import('@ClientShell/Sidebar/components/ClientSidebarItem').then(mod => mod.SidebarItem as ComponentType<any>));
const DynamicViewRenderer = dynamic(() => import('@ClientShell/Renderer/ClientDynamicViewRenderer').then(mod => mod.DynamicViewRenderer as ComponentType<any>));
const SuiteRouter = dynamic(() => import('@ClientShell/Renderer/ClientSuiteRouter').then(mod => mod.SuiteRouter as ComponentType<any>));
const AgencyClientsView = dynamic(() => import('@ClientShell/ClientTemplates/AgencyClients/ClientAgencyClientsView') as Promise<{ default: ComponentType<any> }>);
const ClientDashboardView = dynamic(() => import('@ClientShell/ClientTemplates/ClientDashboard/ClientDashboardView') as Promise<{ default: ComponentType<any> }>);
const ClientManagementView = dynamic(() => import('@ClientShell/ClientTemplates/ClientManagement/ClientManagementView') as Promise<{ default: ComponentType<any> }>);
const ClientActivityWidget = dynamic(() => import('@ClientShell/ClientTemplates/ClientManagement/components/ClientActivityWidget/ClientActivityWidget').then(mod => mod.ClientActivityWidget as ComponentType<any>));
const ClientDirectoryWidget = dynamic(() => import('@ClientShell/ClientTemplates/ClientManagement/components/ClientDirectoryWidget/ClientDirectoryWidget').then(mod => mod.ClientDirectoryWidget as ComponentType<any>));
const ClientListWidget = dynamic(() => import('@ClientShell/ClientTemplates/ClientManagement/components/ClientListWidget/ClientListWidget').then(mod => mod.ClientListWidget as ComponentType<any>));
const ClientsStatsWidget = dynamic(() => import('@ClientShell/ClientTemplates/ClientManagement/components/ClientsStatsWidget/ClientsStatsWidget').then(mod => mod.ClientsStatsWidget as ComponentType<any>));
const StageDropdown = dynamic(() => import('@ClientShell/ClientTemplates/ClientManagement/components/StageDropdown/ClientStageDropdown').then(mod => mod.StageDropdown as ComponentType<any>));
const ClientManagementOverview = dynamic(() => import('@ClientShell/ClientTemplates/ClientManagement/views/ClientManagementOverview') as Promise<{ default: ComponentType<any> }>);
const ClientResourcesView = dynamic(() => import('@ClientShell/ClientTemplates/ClientResources/ClientResourcesView') as Promise<{ default: ComponentType<any> }>);
const IFrameView = dynamic(() => import('@ClientShell/ClientTemplates/CustomSuites/IFrameView/ClientIFrameView') as Promise<{ default: ComponentType<any> }>);
const LivePhaseView = dynamic(() => import('@ClientShell/ClientTemplates/PhasesHub/phases/LiveOps/ClientLivePhaseView') as Promise<{ default: ComponentType<any> }>);
const OnboardingPhaseView = dynamic(() => import('@ClientShell/ClientTemplates/PhasesHub/phases/Onboarding/ClientOnboardingPhaseView') as Promise<{ default: ComponentType<any> }>);
const DiscoveryPhaseView = dynamic(() => import('@ClientShell/ClientTemplates/PhasesHub/phases/Discovery/ClientDiscoveryPhaseView') as Promise<{ default: ComponentType<any> }>);
const DesignPhaseView = dynamic(() => import('@ClientShell/ClientTemplates/PhasesHub/phases/Design/ClientDesignPhaseView') as Promise<{ default: ComponentType<any> }>);
const DevelopmentPhaseView = dynamic(() => import('@ClientShell/ClientTemplates/PhasesHub/phases/Development/ClientDevelopmentPhaseView') as Promise<{ default: ComponentType<any> }>);
const EnterpriseProvider = dynamic(() => import('@ClientShell/ClientTemplates/ClientEnterpriseContext').then(mod => mod.EnterpriseProvider as ComponentType<any>));
const FulfillmentView = dynamic(() => import('@ClientShell/ClientTemplates/Fulfillment/ClientFulfillmentView') as Promise<{ default: ComponentType<any> }>);
const FulfillmentAds = dynamic(() => import('@ClientShell/ClientTemplates/Fulfillment/components/ClientFulfillmentAds').then(mod => mod.FulfillmentAds as ComponentType<any>));
const FulfillmentIncubator = dynamic(() => import('@ClientShell/ClientTemplates/Fulfillment/components/ClientFulfillmentIncubator').then(mod => mod.FulfillmentIncubator as ComponentType<any>));
const FulfillmentSocial = dynamic(() => import('@ClientShell/ClientTemplates/Fulfillment/components/ClientFulfillmentSocial').then(mod => mod.FulfillmentSocial as ComponentType<any>));
const FulfillmentWidget = dynamic(() => import('@ClientShell/ClientTemplates/Fulfillment/components/FulfillmentWidget/ClientFulfillmentWidget').then(mod => mod.FulfillmentWidget as ComponentType<any>));
const ProjectChat = dynamic(() => import('@ClientShell/ClientTemplates/Fulfillment/components/ProjectChat/ClientProjectChat').then(mod => mod.ProjectChat as ComponentType<any>));
const ProjectListWidget = dynamic(() => import('@ClientShell/ClientTemplates/Fulfillment/components/ProjectListWidget/ClientProjectListWidget').then(mod => mod.ProjectListWidget as ComponentType<any>));
const ProjectTimeline = dynamic(() => import('@ClientShell/ClientTemplates/Fulfillment/components/ProjectTimeline/ClientProjectTimeline').then(mod => mod.ProjectTimeline as ComponentType<any>));
const ProjectsStatsWidget = dynamic(() => import('@ClientShell/ClientTemplates/Fulfillment/components/ProjectsStatsWidget/ClientProjectsStatsWidget').then(mod => mod.ProjectsStatsWidget as ComponentType<any>));
const TaskBoardWidget = dynamic(() => import('@ClientShell/ClientTemplates/Fulfillment/components/TaskBoardWidget/ClientTaskBoardWidget').then(mod => mod.TaskBoardWidget as ComponentType<any>));
const TaskListWidget = dynamic(() => import('@ClientShell/ClientTemplates/Fulfillment/components/TaskListWidget/ClientTaskListWidget').then(mod => mod.TaskListWidget as ComponentType<any>));
const TasksStatsWidget = dynamic(() => import('@ClientShell/ClientTemplates/Fulfillment/components/TasksStatsWidget/ClientTasksStatsWidget').then(mod => mod.TasksStatsWidget as ComponentType<any>));
const FulfillmentOverview = dynamic(() => import('@ClientShell/ClientTemplates/Fulfillment/views/ClientFulfillmentOverview') as Promise<{ default: ComponentType<any> }>);
const PortalView = dynamic(() => import('@ClientShell/ClientTemplates/PortalView/ClientPortalView') as Promise<{ default: ComponentType<any> }>);
const RevenueProvider = dynamic(() => import('@ClientShell/ClientTemplates/ClientRevenueContext').then(mod => mod.RevenueProvider as ComponentType<any>));
const WebStudioView = dynamic(() => import('@ClientShell/ClientTemplates/WebStudio/ClientWebStudioView').then(mod => mod.WebStudioView as ComponentType<any>));

const TemplateHubView = dynamic(() => import('@ClientShell/components/TemplateHub/ClientTemplateHubView').then(mod => mod.TemplateHubView as ComponentType<any>));
const PhasesHubView = dynamic(() => import('@ClientShell/ClientTemplates/PhasesHub/ClientPhasesHubView') as Promise<{ default: ComponentType<any> }>);

export const autoComponentMap: Record<string, ComponentType<any>> = {
  TemplateHubView,
  'template-hub': TemplateHubView,
  LoginView,
  'login': LoginView,
  SecurityCheckView,
  WelcomeScreen,
  BridgeControlView,
  'bridge-control-view': BridgeControlView,
  ModalManager,
  'modal-manager': ModalManager,
  GlobalTasksModal,
  'global-tasks-modal': GlobalTasksModal,
  InboxModal,
  'inbox-modal': InboxModal,
  NotificationsModal,
  'notifications-modal': NotificationsModal,
  AgencyConfiguratorView,
  'agency-configurator': AgencyConfiguratorView,
  GlobalSettingsView,
  'global-settings': GlobalSettingsView,
  IntegrationsView,
  'integrations': IntegrationsView,
  AgencyBuilderView,
  'agency-builder': AgencyBuilderView,
  AllUsersView,
  'all-users': AllUsersView,
  DashboardView,
  'dashboard-view': DashboardView,
  EditableText,
  'editable-text': EditableText,
  SubNavBar,
  'sub-nav-bar': SubNavBar,
  ClientTopBar,
  'top-bar': ClientTopBar,
  AppFrame,
  'app-frame': AppFrame,
  ClientSidebarContent,
  'sidebar-content': ClientSidebarContent,
  Search,
  SidebarItem,
  'sidebar-item': SidebarItem,
  DynamicViewRenderer,
  'dynamic-view-renderer': DynamicViewRenderer,
  SuiteRouter,
  'suite-router': SuiteRouter,
  ClientAgencyClientsView: AgencyClientsView,
  'agency-clients': AgencyClientsView,
  ClientDashboardView,
  'client-dashboard': ClientDashboardView,
  ClientManagementView,
  'client-management': ClientManagementView,
  ClientActivityWidget,
  'client-activity': ClientActivityWidget,
  ClientDirectoryWidget,
  'client-directory': ClientDirectoryWidget,
  ClientListWidget,
  'client-list': ClientListWidget,
  ClientsStatsWidget,
  'clients-stats': ClientsStatsWidget,
  StageDropdown,
  'stage-dropdown': StageDropdown,
  ClientManagementOverview,
  'client-management-overview': ClientManagementOverview,
  ClientResourcesView,
  'client-resources': ClientResourcesView,
  IFrameView,
  'i-frame': IFrameView,
  LivePhaseView,
  'live-phase': LivePhaseView,
  OnboardingPhaseView,
  'onboarding-phase': OnboardingPhaseView,
  EnterpriseProvider,
  'enterprise-provider': EnterpriseProvider,
  FulfillmentView,
  'fulfillment': FulfillmentView,
  FulfillmentAds,
  'fulfillment-ads': FulfillmentAds,
  FulfillmentIncubator,
  'fulfillment-incubator': FulfillmentIncubator,
  FulfillmentSocial,
  'fulfillment-social': FulfillmentSocial,
  FulfillmentWidget,
  ProjectChat,
  'project-chat': ProjectChat,
  ProjectListWidget,
  'project-list': ProjectListWidget,
  ProjectTimeline,
  'project-timeline': ProjectTimeline,
  ProjectsStatsWidget,
  'projects-stats': ProjectsStatsWidget,
  TaskBoardWidget,
  'task-board': TaskBoardWidget,
  TaskListWidget,
  'task-list': TaskListWidget,
  TasksStatsWidget,
  'tasks-stats': TasksStatsWidget,
  FulfillmentOverview,
  'fulfillment-overview': FulfillmentOverview,
  PortalView,
  'portal': PortalView,
  RevenueProvider,
  'revenue-provider': RevenueProvider,
  WebStudioView,
  'web-studio': WebStudioView,
  
  // Website Suite Explicit Mappings
  'clients-hub-suite': SuiteRouter,
  'website-suite': SuiteRouter,
  'phases-hub': PhasesHubView,
  'PayloadEditor': IFrameView,
  'WebStudioDashboard': WebStudioView,
  'WebsiteAnalytics': WebStudioView,

  // Phases Hub Mapping
  'discovery-phase-view': DiscoveryPhaseView,
  'design-phase-view': DesignPhaseView,
  'development-phase-view': DevelopmentPhaseView,
  'onboarding-phase-view': OnboardingPhaseView,
  'live-phase-view': LivePhaseView,

  // Manual Mappings
  'welcome-screen': WelcomeScreen,
  'login-view': LoginView,
  'security-check': SecurityCheckView,
  'bridge-control': BridgeControlView,
};

export type WidgetName = string;
export type ViewName = string;
