import { X, Mail, ShieldCheck, User, Clock, Settings2 } from 'lucide-react';

export const employeeProfileModalUI = {
  overlay: 'fixed inset-0 z-50 flex items-center justify-center p-4',
  backdrop: {
    motion: { initial: { opacity: 0 }, animate: { opacity: 1 }, exit: { opacity: 0 } },
    className: 'absolute inset-0 bg-black/60 backdrop-blur-sm',
  },
  modal: {
    motion: { initial: { opacity: 0, scale: 0.95, y: 20 }, animate: { opacity: 1, scale: 1, y: 0 }, exit: { opacity: 0, scale: 0.95, y: 20 } },
    base: 'relative w-full max-w-4xl bg-slate-900 border border-white/10 rounded-[2.5rem] shadow-2xl overflow-hidden',
  },
  header: {
    base: 'flex items-center justify-between px-8 py-6 border-b border-white/10',
    title: 'text-xl font-semibold',
    closeButton: 'p-2 text-slate-400 hover:text-white hover:bg-white/10 rounded-xl transition-colors',
    closeIcon: X,
    closeIconSize: 'w-5 h-5',
  },
  body: 'p-8 md:p-10 overflow-y-auto max-h-[80vh] custom-scrollbar',
  profileSection: {
    base: 'flex flex-col md:flex-row items-center gap-6 md:gap-8 mb-12 text-center md:text-left',
    avatar: 'w-20 h-20 md:w-24 md:h-24 rounded-[1.5rem] md:rounded-[2rem] bg-indigo-600 text-white flex items-center justify-center text-3xl md:text-4xl font-bold shadow-2xl shadow-indigo-600/30',
    name: 'text-3xl md:text-4xl font-semibold mb-2',
    metaRow: 'flex flex-col md:flex-row items-center gap-2 md:gap-4 text-slate-400 text-sm md:text-base',
    metaItem: 'flex items-center gap-1',
    mailIcon: Mail,
    shieldIcon: ShieldCheck,
    metaIconSize: 'w-4 h-4',
  },
  grid: 'grid grid-cols-1 md:grid-cols-2 gap-8',
  card: {
    base: 'glass-card p-8 rounded-[2.5rem] space-y-6',
    sectionHeader: 'text-xl font-medium flex items-center gap-2',
    infoIcon: User,
    availabilityIcon: Clock,
    iconSize: 'w-5 h-5',
    infoIconColor: 'text-indigo-400',
    availabilityIconColor: 'text-emerald-400',
    fieldContainer: 'space-y-4',
    field: {
      base: 'space-y-2',
      label: 'text-[10px] uppercase tracking-widest font-bold text-slate-500',
      input: 'w-full px-4 py-3 bg-white/5 border border-white/10 rounded-xl outline-none focus:border-indigo-500 transition-all',
      textarea: 'w-full px-4 py-3 bg-white/5 border border-white/10 rounded-xl outline-none focus:border-indigo-500 transition-all resize-none',
      inputWithIconWrapper: 'relative',
      inputWithIcon: 'w-full pl-12 pr-4 py-3 bg-white/5 border border-white/10 rounded-xl outline-none focus:border-indigo-500 transition-all',
      iconInside: 'absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-500',
      clockIcon: Clock,
    },
    statusCard: {
      base: 'p-4 bg-emerald-500/10 border border-emerald-500/20 rounded-2xl',
      label: 'text-emerald-400 text-xs font-bold uppercase tracking-widest mb-1',
      statusRow: 'flex items-center gap-2',
      dot: 'w-2 h-2 rounded-full bg-emerald-500 animate-pulse',
      text: 'text-sm font-medium',
    },
  },
  footer: {
    base: 'mt-8 flex justify-end gap-4',
    cancelButton: 'px-8 py-3 bg-white/5 hover:bg-white/10 rounded-xl font-semibold transition-all',
    saveButton: 'px-8 py-3 bg-indigo-600 hover:bg-indigo-500 text-white font-semibold rounded-xl transition-all shadow-lg shadow-indigo-600/20',
    editButton: 'px-8 py-3 bg-white/5 hover:bg-white/10 border border-white/10 rounded-xl font-semibold transition-all flex items-center gap-2',
    editIcon: Settings2,
    editIconSize: 'w-4 h-4',
  },
  text: {
    title: 'Employee Profile',
    generalInfoTitle: 'General Information',
    availabilityTitle: 'Availability',
    fullNameLabel: 'Full Name',
    bioLabel: 'Bio / Role Description',
    bioPlaceholder: 'Describe your role and impact...',
    workingHoursLabel: 'Working Hours',
    workingHoursDefault: '9:00 AM - 5:00 PM',
    workingHoursPlaceholder: 'e.g. Mon-Fri, 9-5',
    statusLabel: 'Status',
    statusText: 'Currently Online',
    cancelText: 'Cancel',
    saveText: 'Save Changes',
    editText: 'Edit Profile',
  },
};
