import { XCircle, Calendar, CheckCircle2, BookOpen, ExternalLink, Download } from 'lucide-react';

export const taskDetailModalUI = {
  overlay: 'fixed inset-0 z-[110] flex items-center justify-center p-6',
  backdrop: {
    motion: { initial: { opacity: 0 }, animate: { opacity: 1 }, exit: { opacity: 0 } },
    className: 'absolute inset-0 bg-slate-950/80 backdrop-blur-md',
  },
  modal: 'relative w-full max-w-2xl glass-card rounded-2xl md:rounded-[2.5rem] p-6 md:p-10 overflow-hidden max-h-[90vh] overflow-y-auto',
  header: {
    base: 'flex items-center justify-between mb-6 md:mb-8',
    statusContainer: 'flex items-center gap-3',
    statusDot: {
      base: 'w-2 h-2 md:w-3 md:h-3 rounded-full',
      backlog: 'bg-slate-500',
      inProgress: 'bg-indigo-500',
      review: 'bg-amber-500',
      done: 'bg-emerald-500',
    },
    statusLabel: 'text-[9px] md:text-[10px] font-bold text-slate-500 uppercase tracking-widest',
    closeButton: 'p-2 hover:bg-white/5 rounded-full transition-colors',
    closeIcon: XCircle,
    closeIconSize: 'w-5 h-5 md:w-6 md:h-6 text-slate-500',
  },
  title: 'text-2xl md:text-3xl font-bold mb-3 md:mb-4',
  description: 'text-sm md:text-base text-slate-400 mb-8 md:mb-10 leading-relaxed',
  metaGrid: 'grid grid-cols-1 sm:grid-cols-2 gap-4 md:gap-6 mb-8 md:mb-10',
  metaCard: {
    base: 'space-y-3 md:space-y-4 p-4 md:p-6 bg-white/[0.02] rounded-2xl md:rounded-3xl border border-white/5',
    label: 'text-[9px] md:text-[10px] font-bold text-slate-500 uppercase tracking-widest',
    assigneeRow: 'flex items-center gap-3',
    avatar: 'w-8 h-8 md:w-10 md:h-10 rounded-lg md:rounded-xl bg-indigo-600 text-white flex items-center justify-center font-bold text-sm md:text-base',
    name: 'font-semibold text-sm md:text-base',
    role: 'text-[9px] md:text-[10px] text-slate-500 uppercase tracking-widest',
    dateRow: 'flex items-center gap-3 text-slate-300',
    calendarIcon: Calendar, // This line was already correct
    calendarIconClass: 'w-4 h-4 md:w-5 md:h-5 text-[var(--color-primary)]',
    dateText: 'font-medium text-sm md:text-base',
  },
  subtasks: {
    container: 'space-y-6 mb-10',
    header: 'flex items-center justify-between',
    title: 'text-lg font-semibold',
    counter: 'text-xs text-slate-500 font-bold',
    list: 'space-y-3',
    itemCompleted: 'w-full flex items-center gap-4 p-4 rounded-2xl border transition-all text-left bg-[var(--color-primary)]/10 border-[var(--color-primary)]/20 text-[var(--color-primary)]',
    itemIncomplete: 'w-full flex items-center gap-4 p-4 rounded-2xl border transition-all text-left bg-white/5 border-white/5 text-slate-400 hover:bg-white/10',
    checkboxCompleted: 'w-5 h-5 rounded-lg border-2 flex items-center justify-center transition-all bg-indigo-500 border-indigo-500',
    checkboxIncomplete: 'w-5 h-5 rounded-lg border-2 flex items-center justify-center transition-all border-white/10',
    checkIcon: CheckCircle2,
    checkIconClass: 'w-3.5 h-3.5 text-white',
    stepText: 'text-sm font-medium',
    stepTextCompleted: 'line-through opacity-50',
  },
  attachments: {
    container: 'space-y-6',
    title: 'text-lg font-semibold',
    grid: 'grid grid-cols-1 sm:grid-cols-2 gap-3 md:gap-4',
    item: 'flex items-center gap-4 p-4 bg-white/5 border border-white/5 rounded-2xl hover:bg-white/10 transition-all group',
    iconContainer: { // This line was already correct
      sop: 'p-2 rounded-lg bg-[var(--color-primary)]/20 text-[var(--color-primary)]',
      link: 'p-2 rounded-lg bg-amber-500/20 text-amber-400', // This line was already correct
      download: 'p-2 rounded-lg bg-emerald-500/20 text-emerald-400',
    },
    icons: { sop: BookOpen, link: ExternalLink, download: Download },
    iconSize: 'w-4 h-4',
    textContainer: 'flex-1 overflow-hidden',
    name: 'text-xs font-semibold truncate',
    type: 'text-[10px] text-slate-500 uppercase tracking-widest',
  },
  text: {
    noDate: 'No Due Date',
    assigneeLabel: 'Assignee',
    timelineLabel: 'Timeline',
    subTasksTitle: 'Sub-tasks',
    attachmentsTitle: 'Attachments',
    completeSuffix: 'Complete',
  },
};
