import { Plus, Trash2, GripVertical, CheckCircle2, LayoutTemplate, Link as LinkIcon, Save, Layout, Shield, Layers } from 'lucide-react';

export const agencyBuilderViewUI = {
  container: {
    base: 'p-4 md:p-10 max-w-6xl mx-auto w-full',
    animation: {
      key: 'agency-builder',
      initial: { opacity: 0, y: 10 },
      animate: { opacity: 1, y: 0 },
      exit: { opacity: 0, y: -10 },
    },
  },
  header: {
    base: 'flex flex-col md:flex-row md:items-center justify-between gap-6 mb-8 md:mb-10',
    titleStyle: 'text-2xl md:text-3xl font-semibold mb-2',
    subtitleStyle: 'text-sm md:text-base text-slate-500',
    text: {
      title: 'App Builder',
      subtitle: 'Customize your portal structure, custom pages, and roles.',
    },
  },
  tabs: {
    base: 'flex gap-2 md:gap-4 mb-6 md:mb-8 border-b border-white/10 pb-4 overflow-x-auto no-scrollbar',
    button: {
      base: 'flex items-center gap-2 px-3 md:px-4 py-2 rounded-xl transition-colors whitespace-nowrap text-xs md:text-sm',
      active: 'bg-[var(--color-primary)]/20 text-[var(--color-primary)]',
      inactive: 'text-slate-400 hover:bg-white/5 hover:text-white',
    },
    items: [
      { id: 'navigation', label: 'Navigation', icon: LinkIcon },
      { id: 'layouts', label: 'View Layouts', icon: Layers },
      { id: 'pages', label: 'Custom Pages', icon: Layout },
      { id: 'roles', label: 'Roles', icon: Shield },
    ],
  },
  navigation: {
    grid: 'grid grid-cols-1 lg:grid-cols-3 gap-6 md:gap-8 mb-10',
    templatesSection: {
      base: 'lg:col-span-1 space-y-6',
      card: 'glass-card p-5 md:p-6 rounded-2xl md:rounded-3xl',
      titleStyle: 'text-lg md:text-xl font-medium mb-5 md:mb-6 flex items-center gap-2',
      titleIcon: LayoutTemplate,
      titleIconSize: 'w-5 h-5 text-[var(--color-primary)]',
      titleText: 'Templates',
      list: 'space-y-4',
      templateCard: {
        active: 'bg-[var(--color-primary)]/20 border-[var(--color-primary)]/50',
        inactive: 'bg-white/5 border-white/10 hover:border-white/20',
        base: 'p-4 rounded-xl md:rounded-2xl border transition-all',
        headerRow: 'flex justify-between items-start mb-2',
        name: 'font-medium text-white text-sm md:text-base',
        activeIcon: CheckCircle2,
        activeIconSize: 'w-4 h-4 md:w-5 md:h-5 text-[var(--color-primary)]',
        description: 'text-[10px] md:text-xs text-slate-400 mb-4',
        activateButton: {
          base: 'w-full py-2 rounded-lg md:rounded-xl text-xs md:text-sm font-medium transition-colors',
          active: 'bg-[var(--color-primary)] text-white',
          inactive: 'bg-white/10 text-slate-300 hover:bg-white/20',
        },
        text: {
          activateLabel: 'Activate',
          activeLabel: 'Active',
        },
      },
    },
    sidebarSection: {
      base: 'lg:col-span-2 space-y-6',
      card: 'glass-card p-5 md:p-6 rounded-2xl md:rounded-3xl',
      header: 'flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-6',
      titleStyle: 'text-lg md:text-xl font-medium flex items-center gap-2',
      titleIcon: LinkIcon,
      titleIconSize: 'w-5 h-5 text-emerald-400',
      titleText: 'Sidebar Navigation',
      headerActions: 'flex gap-2 md:gap-3',
      addButton: 'flex-1 sm:flex-none px-3 md:px-4 py-2 bg-white/5 hover:bg-white/10 text-white text-xs md:text-sm font-medium rounded-lg md:rounded-xl border border-white/10 transition-all flex items-center justify-center gap-2',
      addIcon: Plus,
      addIconSize: 'w-3.5 h-3.5 md:w-4 md:h-4',
      saveButton: 'flex-1 sm:flex-none px-3 md:px-4 py-2 bg-[var(--color-primary)] hover:brightness-110 text-white text-xs md:text-sm font-medium rounded-lg md:rounded-xl transition-all flex items-center justify-center gap-2',
      saveIcon: Save,
      saveIconSize: 'w-3.5 h-3.5 md:w-4 md:h-4',
      text: {
        addLinkText: 'Add Link',
        saveChangesText: 'Save Changes',
        emptyState: 'No custom links defined. Add one or activate a template.',
        standardViewsGroup: 'Standard Views',
        customPagesGroup: 'Custom Pages',
      },
      linkList: 'space-y-3',
      linkEmpty: 'text-center py-10 text-slate-500 border border-dashed border-white/10 rounded-xl md:rounded-2xl text-sm',
      linkRow: {
        base: 'flex flex-col md:flex-row md:items-center gap-4 p-4 bg-white/5 border border-white/5 rounded-xl md:rounded-2xl group relative',
        grip: 'hidden md:block cursor-grab active:cursor-grabbing text-slate-600 hover:text-slate-400',
        gripIcon: GripVertical,
        gripIconSize: 'w-5 h-5',
        fieldsGrid: 'flex-1 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4',
        label: 'text-[9px] md:text-[10px] uppercase tracking-widest text-slate-500 mb-1 block',
        input: 'w-full bg-black/20 border border-white/10 rounded-lg px-3 py-1.5 md:py-2 text-xs md:text-sm text-white focus:border-[var(--color-primary)] outline-none',
        select: 'w-full bg-black/20 border border-white/10 rounded-lg px-3 py-1.5 md:py-2 text-xs md:text-sm text-white focus:border-[var(--color-primary)] outline-none',
        colSpan: 'sm:col-span-2 lg:col-span-1',
        removeButton: 'absolute top-2 right-2 md:static p-2 text-slate-600 hover:text-red-400 transition-colors rounded-lg hover:bg-red-500/10',
        removeIcon: Trash2,
        removeIconSize: 'w-4 h-4 md:w-5 md:h-5',
        text: {
          labelField: 'Label',
          iconField: 'Icon Name',
          iconPlaceholder: 'e.g. Users, Layout',
          viewField: 'Target View',
        },
      },
      standardViewOptions: [
        { value: 'dashboard', label: 'Dashboard' },
        { value: 'agency-clients', label: 'Clients' },
        { value: 'project-hub', label: 'Projects' },
        { value: 'inbox', label: 'Inbox' },
        { value: 'employee-management', label: 'Team' },
        { value: 'global-activity', label: 'Activity Logs' },
        { value: 'ai-sessions', label: 'AI Monitor' },
        { value: 'agency-builder', label: 'App Builder' },
      ],
    },
  },
};
