import { Layout, Plus, Save, Trash2, Edit2 } from 'lucide-react';

export const pageBuilderUI = {
  card: 'glass-card p-5 md:p-8 rounded-2xl md:rounded-3xl',
  header: {
    base: 'flex flex-col md:flex-row md:items-center justify-between gap-6 mb-6 md:mb-8',
    titleStyle: 'text-xl md:text-2xl font-semibold flex items-center gap-3',
    icon: Layout,
    iconSize: 'w-5 h-5 md:w-6 md:h-6 text-[var(--color-primary)]',
    actions: 'flex gap-3',
    cancelButton: 'flex-1 md:flex-none px-4 py-2 bg-white/5 hover:bg-white/10 rounded-xl transition-colors text-xs md:text-sm',
    saveButton: 'flex-1 md:flex-none px-4 py-2 bg-[var(--color-primary)] hover:brightness-110 rounded-xl transition-colors flex items-center justify-center gap-2 text-xs md:text-sm',
    createButton: 'w-full md:w-auto px-4 py-2 bg-[var(--color-primary)] hover:brightness-110 rounded-xl transition-colors flex items-center justify-center gap-2 text-xs md:text-sm',
    saveIcon: Save,
    saveIconSize: 'w-3.5 h-3.5 md:w-4 md:h-4',
    createIcon: Plus,
    createIconSize: 'w-3.5 h-3.5 md:w-4 md:h-4',
  },
  text: {
    editTitlePrefix: 'Edit Page:',
    listTitle: 'Custom Pages',
    widgetsTitle: 'Widgets',
    pageTitleLabel: 'Page Title',
    slugLabel: 'Slug (URL Path)',
    cancelText: 'Cancel',
    savePageText: 'Save Page',
    createPageText: 'Create Page',
    addWidgetText: 'Add Widget',
    noWidgets: 'No widgets added yet.',
    noPages: 'No custom pages created yet. Build your first dashboard!',
  },
  formGrid: 'grid grid-cols-1 md:grid-cols-2 gap-4 md:gap-6 mb-6 md:mb-8',
  label: 'text-[10px] md:text-xs uppercase tracking-widest text-slate-500 mb-2 block',
  input: 'w-full bg-slate-900/50 border border-white/10 rounded-xl p-2.5 md:p-3 text-xs md:text-sm text-white focus:outline-none focus:border-[var(--color-primary)]',
  widgetSectionHeader: {
    base: 'mb-5 md:mb-6 flex items-center justify-between',
    title: 'text-base md:text-lg font-medium',
    addButton: 'px-3 py-1.5 bg-white/5 hover:bg-white/10 rounded-lg text-xs md:text-sm flex items-center gap-2 transition-colors',
    addIcon: Plus,
    addIconSize: 'w-3.5 h-3.5 md:w-4 md:h-4',
  },
  widgetList: 'space-y-3 md:space-y-4',
  widgetEmpty: 'text-center py-8 text-slate-500 border border-dashed border-white/10 rounded-xl md:rounded-2xl text-sm',
  widgetRow: {
    base: 'p-4 bg-white/5 border border-white/5 rounded-xl md:rounded-2xl flex flex-col sm:flex-row gap-4 items-start relative',
    inner: 'flex-1 w-full space-y-4',
    grid: 'grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4',
    labelSmall: 'text-[9px] md:text-[10px] uppercase tracking-widest text-slate-500 mb-1 block',
    inputSmall: 'w-full bg-slate-900/50 border border-white/10 rounded-lg p-2 text-xs md:text-sm text-white focus:outline-none focus:border-[var(--color-primary)]',
    select: 'w-full bg-slate-900/50 border border-white/10 rounded-lg p-2 text-xs md:text-sm text-white focus:outline-none focus:border-[var(--color-primary)]',
    textarea: 'w-full bg-slate-900/50 border border-white/10 rounded-lg p-2 text-xs md:text-sm text-white focus:outline-none focus:border-[var(--color-primary)] resize-none',
    colSpan: 'sm:col-span-2 lg:col-span-1',
    deleteButton: 'absolute top-2 right-2 sm:static p-2 text-red-400 hover:bg-red-400/10 rounded-lg transition-colors sm:mt-5',
    deleteIcon: Trash2,
    deleteIconSize: 'w-4 h-4',
    textContentLabel: 'text-[9px] md:text-[10px] uppercase tracking-widest text-slate-500 mb-1 block',
    textContentPlaceholder: 'Enter text content here...',
  },
  widgetTypeOptions: [
    { value: 'metric', label: 'Metric Card' },
    { value: 'chart', label: 'Chart' },
    { value: 'list', label: 'Data List' },
    { value: 'text', label: 'Text Block' },
  ],
  widgetSizeOptions: [
    { value: 'small', label: 'Small (1/4)' },
    { value: 'medium', label: 'Medium (1/2)' },
    { value: 'large', label: 'Large (3/4)' },
    { value: 'full', label: 'Full Width' },
  ],
  pageList: 'space-y-3 md:space-y-4',
  pageEmpty: 'text-center py-10 text-slate-500 border border-dashed border-white/10 rounded-xl md:rounded-2xl text-sm',
  pageRow: {
    base: 'flex items-center justify-between p-3 md:p-4 bg-white/5 rounded-xl md:rounded-2xl border border-white/5 hover:border-white/10 transition-colors',
    info: 'min-w-0',
    title: 'font-medium text-white text-sm md:text-base truncate',
    detail: 'text-[10px] md:text-xs text-slate-500 truncate',
    actions: 'flex items-center gap-1 md:gap-2 shrink-0',
    editButton: 'p-2 text-slate-400 hover:text-white hover:bg-white/5 rounded-lg transition-colors',
    editIcon: Edit2,
    deleteButton: 'p-2 text-red-400 hover:bg-red-400/10 rounded-lg transition-colors',
    deleteIcon: Trash2,
    iconSize: 'w-3.5 h-3.5 md:w-4 md:h-4',
  },
};
